<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xmiexport" nsURI="http://www.eclipse.org/fordiac/ide/xmiexport/XMIExport"
    nsPrefix="xmiexport">
  <eClassifiers xsi:type="ecore:EClass" name="XMIExportAttributeValues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeValues" upperBound="-1"
        eType="#//XMIExportAttributeValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMIExportAttributeValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../org.eclipse.fordiac.ide.structuredtextcore.model/model/STCore.ecore#//STInitializerExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMIExportInitialValues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialValues" upperBound="-1"
        eType="#//XMIExportInitialValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMIExportInitialValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//VarDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../org.eclipse.fordiac.ide.structuredtextcore.model/model/STCore.ecore#//STInitializerExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMIExportTypeDeclarations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeDeclarations" upperBound="-1"
        eType="#//XMIExportTypeDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMIExportTypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//VarDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeDeclaration" eType="ecore:EClass ../../org.eclipse.fordiac.ide.structuredtextcore.model/model/STCore.ecore#//STTypeDeclaration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultType" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//INamedElement"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
