version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Github Action Dependencies"
    groups:
      codeql:
        patterns:
          - "github/codeql-action*"
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - dependencies
