/*******************************************************************************
 * Copyright (c) 2026 Primetals Technologies Austria GmbH
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Oberlehner - initial API and implementation and/or initial documentation
 *******************************************************************************/
package org.eclipse.fordiac.ide.export.refactoring;

import java.text.MessageFormat;
import java.util.function.UnaryOperator;

import org.eclipse.core.resources.IFolder;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.fordiac.ide.export.Messages;
import org.eclipse.fordiac.ide.export.utils.AdditionalSourceDirectories;
import org.eclipse.ltk.core.refactoring.Change;
import org.eclipse.ltk.core.refactoring.RefactoringStatus;
import org.eclipse.ltk.core.refactoring.participants.CheckConditionsContext;
import org.eclipse.ltk.core.refactoring.participants.RenameParticipant;

/**
 * A participant that keeps the output and additional source directories of the
 * type export in sync when a referred folder is renamed.
 */
public class RenameSourceDirectoryParticipant extends RenameParticipant {

	private IFolder folder;

	@Override
	protected boolean initialize(final Object element) {
		if (element instanceof final IFolder renamedFolder && renamedFolder.getProject().isAccessible()
				&& (UpdateSourceDirectoriesChange.isReferenced(renamedFolder)
						|| containsOutputDirectory(renamedFolder))) {
			folder = renamedFolder;
			return true;
		}
		return false;
	}

	@Override
	public String getName() {
		return Messages.Refactoring_RenameSourceDirectoryParticipant;
	}

	@Override
	public RefactoringStatus checkConditions(final IProgressMonitor pm, final CheckConditionsContext context) {
		if (containsOutputDirectory(folder)) {
			return new RefactoringStatus();
		}
		final String newName = getArguments().getNewName();
		if (!AdditionalSourceDirectories.isValidDirectoryName(newName)) {
			return RefactoringStatus.createWarningStatus(
					MessageFormat.format(Messages.Refactoring_InvalidSourceDirectoryName, newName));
		}
		if (isGeneratedDirectory(getNewPath())) {
			return RefactoringStatus.createWarningStatus(
					MessageFormat.format(Messages.Refactoring_GeneratedSourceDirectoryName, newName));
		}
		return new RefactoringStatus();
	}

	@Override
	public Change createChange(final IProgressMonitor pm) {
		final IPath oldPath = folder.getProjectRelativePath();
		final IPath newPath = getNewPath();
		final UnaryOperator<IPath> relocate = directory -> newPath
				.append(directory.removeFirstSegments(oldPath.segmentCount()));
		return UpdateSourceDirectoriesChange.create(folder,
				keepsSourceDirectories(newPath) ? relocate : directory -> null, relocate);
	}

	private IPath getNewPath() {
		return folder.getProjectRelativePath().removeLastSegments(1).append(getArguments().getNewName());
	}

	private boolean keepsSourceDirectories(final IPath newPath) {
		return containsOutputDirectory(folder)
				|| (AdditionalSourceDirectories.isValidDirectoryName(getArguments().getNewName())
						&& !isGeneratedDirectory(newPath));
	}

	/**
	 * Directories generated by the export filter are recreated on every export,
	 * therefore source directories moved into them can no longer be preserved.
	 */
	private boolean isGeneratedDirectory(final IPath newPath) {
		return AdditionalSourceDirectories
				.isGeneratedDirectory(AdditionalSourceDirectories.getOutputDirectory(folder.getProject()), newPath);
	}

	private static boolean containsOutputDirectory(final IFolder folder) {
		return folder.getProjectRelativePath()
				.isPrefixOf(AdditionalSourceDirectories.getOutputDirectory(folder.getProject()));
	}
}
