<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="data" nsURI="org.eclipse.fordiac.ide.model.datatype" nsPrefix="data">
  <eClassifiers xsi:type="ecore:EClass" name="ArrayType" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subranges" lowerBound="1"
        upperBound="-1" eType="#//Subrange" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Subrange"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValues" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="InitialValues"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseType" eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BaseType1">
    <eLiterals name="DATEANDTIME" literal="DATE_AND_TIME"/>
    <eLiterals name="BYTE" value="1"/>
    <eLiterals name="SINT" value="2"/>
    <eLiterals name="USINT" value="3"/>
    <eLiterals name="LWORD" value="4"/>
    <eLiterals name="TIME" value="5"/>
    <eLiterals name="WORD" value="6"/>
    <eLiterals name="STRING" value="7"/>
    <eLiterals name="BOOL" value="8"/>
    <eLiterals name="LREAL" value="9"/>
    <eLiterals name="REAL" value="10"/>
    <eLiterals name="LINT" value="11"/>
    <eLiterals name="ULINT" value="12"/>
    <eLiterals name="UINT" value="13"/>
    <eLiterals name="DATE" value="14"/>
    <eLiterals name="DWORD" value="15"/>
    <eLiterals name="INT" value="16"/>
    <eLiterals name="TIMEOFDAY" value="17" literal="TIME_OF_DAY"/>
    <eLiterals name="WSTRING" value="18"/>
    <eLiterals name="DINT" value="19"/>
    <eLiterals name="UDINT" value="20"/>
    <eLiterals name="ANY" value="21"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true" eSuperTypes="lib.ecore#//LibraryElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DirectlyDerivedType" eSuperTypes="#//DerivedType"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumeratedType" eSuperTypes="#//ValueType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumeratedValue" lowerBound="1"
        upperBound="-1" eType="#//EnumeratedValue" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="EnumeratedValue"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumeratedValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="Comment"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="Name"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuredType" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="varDeclaration" upperBound="-1"
        eType="ecore:EClass lib.ecore#//VarDeclaration" volatile="true" transient="true"
        derived="true" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="VarDeclaration"/>
        <details key="namespace" value="http://www.fordiac.org/61499/lib"/>
        <details key="group" value="#group:0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subrange">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Description"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerLimit" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="LowerLimit"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperLimit" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="UpperLimit"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubrangeType" eSuperTypes="#//DerivedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subrange" lowerBound="1"
        eType="#//Subrange" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="Subrange"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarInitialization">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueType" eSuperTypes="#//DataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElementaryType" eSuperTypes="#//ValueType"/>
  <eClassifiers xsi:type="ecore:EClass" name="DerivedType" eSuperTypes="#//ValueType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseType" lowerBound="1"
        eType="#//ElementaryType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventType" eSuperTypes="#//DataType"/>
</ecore:EPackage>
