<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Palette" nsURI="org.eclipse.fordiac.ide.model.Palette" nsPrefix="Palette">
  <eClassifiers xsi:type="ecore:EClass" name="Palette">
    <eOperations name="getAdapterTypesSorted" upperBound="-1" eType="#//AdapterTypePaletteEntry">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.fordiac.ide.model.annotations.PaletteAnnotations.getAdapterTypesSorted(this);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAdapterTypeEntry" lowerBound="1" eType="#//AdapterTypePaletteEntry">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getAdapterTypes().get(typeName);"/>
      </eAnnotations>
      <eParameters name="typeName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getDeviceTypeEntry" lowerBound="1" eType="#//DeviceTypePaletteEntry">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getDeviceTypes().get(typeName);"/>
      </eAnnotations>
      <eParameters name="typeName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getFBTypeEntry" lowerBound="1" eType="#//FBTypePaletteEntry">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getFbTypes().get(typeName);"/>
      </eAnnotations>
      <eParameters name="typeName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getResourceTypeEntry" lowerBound="1" eType="#//ResourceTypeEntry">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getResourceTypes().get(typeName);"/>
      </eAnnotations>
      <eParameters name="typeName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getSegmentTypeEntry" lowerBound="1" eType="#//SegmentTypePaletteEntry">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getSegmentTypes().get(typeName);"/>
      </eAnnotations>
      <eParameters name="typeName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getSubAppTypeEntry" lowerBound="1" eType="#//SubApplicationTypePaletteEntry">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getSubAppTypes().get(typeName);"/>
      </eAnnotations>
      <eParameters name="typeName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addPaletteEntry">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="org.eclipse.fordiac.ide.model.annotations.PaletteAnnotations.addTypeEntry(this, entry);"/>
      </eAnnotations>
      <eParameters name="entry" lowerBound="1" eType="#//PaletteEntry"/>
    </eOperations>
    <eOperations name="removePaletteEntry">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="org.eclipse.fordiac.ide.model.annotations.PaletteAnnotations.removeTypeEntry(this, entry);"/>
      </eAnnotations>
      <eParameters name="entry" lowerBound="1" eType="#//PaletteEntry"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="project" eType="#//IProject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="automationSystem" eType="ecore:EClass lib.ecore#//AutomationSystem"
        eOpposite="lib.ecore#//AutomationSystem/palette"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeLibrary" eType="#//TypeLibrary"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adapterTypes" upperBound="-1"
        eType="#//StringToAdapterTypePaletteEntryMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceTypes" upperBound="-1"
        eType="#//StringToFDeviceTypePaletteEntryMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fbTypes" upperBound="-1"
        eType="#//StringToFBTypePaletteEntryMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceTypes" upperBound="-1"
        eType="#//StringToResourceTypeEntryMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentTypes" upperBound="-1"
        eType="#//StringToSegmentTypePaletteEntryMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subAppTypes" upperBound="-1"
        eType="#//StringToSubApplicationTypePaletteEntryMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToAdapterTypePaletteEntryMap"
      instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//AdapterTypePaletteEntry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToFDeviceTypePaletteEntryMap"
      instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//DeviceTypePaletteEntry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToFBTypePaletteEntryMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//FBTypePaletteEntry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToResourceTypeEntryMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ResourceTypeEntry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToSegmentTypePaletteEntryMap"
      instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//SegmentTypePaletteEntry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToSubApplicationTypePaletteEntryMap"
      instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//SubApplicationTypePaletteEntry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaletteEntry" abstract="true">
    <eOperations name="getProjectRelativeTypePath" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getFile().getProjectRelativePath().toOSString();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="loadType" eType="ecore:EClass lib.ecore#//LibraryElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.fordiac.ide.model.annotations.PaletteAnnotations.loadType(this);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getTypeImporter" eType="#//TypeImporter"/>
    <eOperations name="getTypeLibrary" eType="#//TypeLibrary">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getPalette().getTypeLibrary();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" eType="#//IFile"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastModificationTimestamp"
        ordered="false" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Long"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass lib.ecore#//LibraryElement"
        resolveProxies="false" eOpposite="lib.ecore#//LibraryElement/paletteEntry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="palette" lowerBound="1"
        eType="#//Palette" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdapterTypePaletteEntry" eSuperTypes="#//PaletteEntry">
    <eOperations name="getType" eType="ecore:EClass lib.ecore#//AdapterType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="LibraryElement type = super.getType();&#xA;if(type instanceof AdapterType){&#xA;   return (AdapterType) type;&#xA;}&#xA;return null;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="setType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if(type instanceof AdapterType){&#xA;&#x9;super.setType(type);&#xA;}else{&#xA;&#x9;super.setType(null);&#xA;&#x9;if(null != type){&#xA;&#x9;&#x9;&lt;% org.eclipse.core.runtime.Status %> exception = new Status(&lt;%org.eclipse.core.runtime.IStatus%>.ERROR, Activator.PLUGIN_ID, &quot;tried to set no AdapterType as type entry for AdapterTypePaletteEntry&quot;);  //$NON-NLS-1$&#xA;&#x9;&#x9;Activator.getDefault().getLog().log(exception);&#xA;&#x9;}&#xA;}"/>
      </eAnnotations>
      <eParameters name="type" eType="ecore:EClass lib.ecore#//LibraryElement"/>
    </eOperations>
    <eOperations name="getTypeImporter" eType="#//TypeImporter">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return new org.eclipse.fordiac.ide.model.dataimport.ADPImporter();"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypePaletteEntry" eSuperTypes="#//PaletteEntry">
    <eOperations name="getType" lowerBound="1" eType="ecore:EClass data.ecore#//AnyDerivedType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="LibraryElement type = super.getType();&#xA;if (type instanceof AnyDerivedType) {&#xA;&#x9;return (AnyDerivedType) type;&#xA;}&#xA;return null;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="setType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (type instanceof AnyDerivedType) {&#xA;&#x9;super.setType(type);&#xA;} else {&#xA;&#x9;super.setType(null);&#xA;&#x9;if (null != type) {&#xA;&#x9;&#x9;Status exception = new Status(IStatus.ERROR, Activator.PLUGIN_ID,&#xA;&#x9;&#x9;&#x9;&#x9;&quot;tried to set no AnyDerivedType as type entry for DataTypePaletteEntry&quot;); //$NON-NLS-1$&#xA;&#x9;&#x9;Activator.getDefault().getLog().log(exception);&#xA;&#x9;}&#xA;}"/>
      </eAnnotations>
      <eParameters name="type" eType="ecore:EClass lib.ecore#//LibraryElement"/>
    </eOperations>
    <eOperations name="getTypeImporter" eType="#//TypeImporter">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return new org.eclipse.fordiac.ide.model.dataimport.DataTypeImporter();"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceTypePaletteEntry" eSuperTypes="#//PaletteEntry">
    <eOperations name="getDeviceType" lowerBound="1" eType="ecore:EClass lib.ecore#//DeviceType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="LibraryElement type = getType();&#xA;if(type instanceof DeviceType){&#xA;   return (DeviceType) type;&#xA;}&#xA;return null;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="setType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if(type instanceof DeviceType){&#xA;&#x9;super.setType(type);&#xA;}else{&#xA;&#x9;super.setType(null);&#xA;&#x9;if(null != type){&#xA;&#x9;&#x9;&lt;%org.eclipse.core.runtime.Status%> exception = new Status(&lt;%org.eclipse.core.runtime.IStatus%>.ERROR, Activator.PLUGIN_ID, &quot;tried to set no DeviceType as type entry for DeviceTypePaletteEntry&quot;);  //$NON-NLS-1$&#xA;&#x9;&#x9;Activator.getDefault().getLog().log(exception);&#xA;&#x9;}&#xA;}"/>
      </eAnnotations>
      <eParameters name="type" eType="ecore:EClass lib.ecore#//LibraryElement"/>
    </eOperations>
    <eOperations name="getTypeImporter" eType="#//TypeImporter">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return new org.eclipse.fordiac.ide.model.dataimport.DEVImporter();"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBTypePaletteEntry" eSuperTypes="#//PaletteEntry">
    <eOperations name="getFBType" lowerBound="1" eType="ecore:EClass lib.ecore#//FBType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="LibraryElement type = getType();&#xA;if(type instanceof FBType){&#xA;   return (FBType) type;&#xA;}&#xA;return null;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="setType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if(type instanceof FBType){&#xA;&#x9;super.setType(type);&#xA;}else{&#xA;&#x9;super.setType(null);&#xA;&#x9;if(null != type){&#xA;&#x9;&#x9;&lt;%org.eclipse.core.runtime.Status%> exception = new Status(&lt;%org.eclipse.core.runtime.IStatus%>.ERROR, Activator.PLUGIN_ID, &quot;tried to set no FBType as type entry for FBTypePaletteEntry&quot;); //$NON-NLS-1$&#xA;&#x9;&#x9;Activator.getDefault().getLog().log(exception);&#xA;&#x9;}&#xA;}"/>
      </eAnnotations>
      <eParameters name="type" eType="ecore:EClass lib.ecore#//LibraryElement"/>
    </eOperations>
    <eOperations name="getTypeImporter" eType="#//TypeImporter">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return new org.eclipse.fordiac.ide.model.dataimport.FBTImporter();"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceTypeEntry" eSuperTypes="#//PaletteEntry">
    <eOperations name="getResourceType" lowerBound="1" eType="ecore:EClass lib.ecore#//ResourceType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="LibraryElement type = getType();&#xA;if(type instanceof ResourceType){&#xA;   return (ResourceType) type;&#xA;}&#xA;return null;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="setType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if(type instanceof ResourceType){&#xA;&#x9;super.setType(type);&#xA;}else{&#xA;&#x9;super.setType(null);&#xA;&#x9;if(null != type){&#xA;&#x9;&#x9;&lt;%org.eclipse.core.runtime.Status%> exception = new Status(&lt;%org.eclipse.core.runtime.IStatus%>.ERROR, Activator.PLUGIN_ID, &quot;tried to set no ResourceType as type entry for ResourceTypeEntry&quot;); //$NON-NLS-1$&#xA;&#x9;&#x9;Activator.getDefault().getLog().log(exception);&#xA;&#x9;}&#xA;}"/>
      </eAnnotations>
      <eParameters name="type" eType="ecore:EClass lib.ecore#//LibraryElement"/>
    </eOperations>
    <eOperations name="getTypeImporter" eType="#//TypeImporter">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return new org.eclipse.fordiac.ide.model.dataimport.RESImporter();"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentTypePaletteEntry" eSuperTypes="#//PaletteEntry">
    <eOperations name="getSegmentType" lowerBound="1" eType="ecore:EClass lib.ecore#//SegmentType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="LibraryElement type = getType();&#xA;if(type instanceof SegmentType){&#xA;   return (SegmentType) type;&#xA;}&#xA;return null;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="setType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if(type instanceof SegmentType){&#xA;&#x9;super.setType(type);&#xA;}else{&#xA;&#x9;super.setType(null);&#xA;&#x9;if(null != type){&#xA;&#x9;&#x9;&lt;%org.eclipse.core.runtime.Status%> exception = new Status(&lt;%org.eclipse.core.runtime.IStatus%>.ERROR, Activator.PLUGIN_ID, &quot;tried to set no SegmentType as type entry for SegmentTypePaletteEntry&quot;); //$NON-NLS-1$&#xA;&#x9;&#x9;Activator.getDefault().getLog().log(exception);&#xA;&#x9;}&#xA;}"/>
      </eAnnotations>
      <eParameters name="type" eType="ecore:EClass lib.ecore#//LibraryElement"/>
    </eOperations>
    <eOperations name="getTypeImporter" eType="#//TypeImporter">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return new org.eclipse.fordiac.ide.model.dataimport.SEGImporter();"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubApplicationTypePaletteEntry" eSuperTypes="#//PaletteEntry">
    <eOperations name="getSubApplicationType" lowerBound="1" eType="ecore:EClass lib.ecore#//SubAppType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="LibraryElement type = getType();&#xA;if(type instanceof SubAppType){&#xA;   return (SubAppType) type;&#xA;}&#xA;return null;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="setType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if(type instanceof SubAppType){&#xA;&#x9;super.setType(type);&#xA;}else{&#xA;&#x9;super.setType(null);&#xA;&#x9;if(null != type){&#xA;&#x9;&#x9;&lt;%org.eclipse.core.runtime.Status%> exception = new Status(&lt;%org.eclipse.core.runtime.IStatus%>.ERROR, Activator.PLUGIN_ID, &quot;tried to set no SubAppType as type entry for SubApplicationTypePaletteEntry&quot;); //$NON-NLS-1$&#xA;&#x9;&#x9;Activator.getDefault().getLog().log(exception);&#xA;&#x9;}&#xA;}"/>
      </eAnnotations>
      <eParameters name="type" eType="ecore:EClass lib.ecore#//LibraryElement"/>
    </eOperations>
    <eOperations name="getTypeImporter" eType="#//TypeImporter">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return new org.eclipse.fordiac.ide.model.dataimport.SubAppTImporter();"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IFile" instanceClassName="org.eclipse.core.resources.IFile"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IProject" instanceClassName="org.eclipse.core.resources.IProject"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TypeImporter" instanceClassName="org.eclipse.fordiac.ide.model.dataimport.TypeImporter"/>
  <eClassifiers xsi:type="ecore:EDataType" name="XMLStreamException" instanceClassName="javax.xml.stream.XMLStreamException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="CoreException" instanceClassName="org.eclipse.core.runtime.CoreException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TypeLibrary" instanceClassName="org.eclipse.fordiac.ide.model.typelibrary.TypeLibrary"/>
</ecore:EPackage>
