<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="OuterSubApp" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="mario" Date="2024-08-05">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="DI1" Type="BOOL" Comment="" InitialValue="TRUE"/>
			<VarDeclaration Name="DI2" Type="BOOL" Comment="" InitialValue="FALSE"/>
			<VarDeclaration Name="DI3" Type="BOOL" Comment="" InitialValue="TRUE"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="InnerSubApp" Type="InnerSubApp" Comment="" x="633.33" y="138.89">
		</SubApp>
		<FB Name="DIOUTONE" Type="E_PERMIT" Comment="" x="-3033.33" y="811.11">
		</FB>
		<FB Name="DIOUTTWO" Type="PUBLISH_0" Comment="" x="-2777.78" y="-777.78">
		</FB>
		<DataConnections>
			<Connection Source="DI1" Destination="InnerSubApp.DI1" Comment="" dx1="322.22"/>
			<Connection Source="DI3" Destination="DIOUTONE.PERMIT" Comment="" dx1="2011.11"/>
			<Connection Source="DI2" Destination="DIOUTTWO.QI" Comment="" dx1="2027.78"/>
			<Connection Source="DIOUTTWO.QO" Destination="InnerSubApp.DI2" Comment="" dx1="1494.44"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
