<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="monitoringbase" nsURI="org.eclipse.fordiac.depolyment.monitoringbase"
    nsPrefix="monitoringbase">
  <eClassifiers xsi:type="ecore:EClass" name="MonitoringBaseElement" abstract="true"
      eSuperTypes="#//IEditPartCreator">
    <eOperations name="getPortString" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="StringBuilder portString = new StringBuilder();&#xA;&#xA;portString.append(getPort().getHierarchy());&#xA;&#xA;&#xA;if (getPort().getInterfaceElement().eContainer() != null &amp;&amp; getPort().getInterfaceElement().eContainer().eContainer() instanceof AdapterFB) {&#xA;&#x9;portString.append(((PortElementImpl) getPort().eContainer()).getInterfaceElement().getName());&#xA;&#x9;portString.append(&quot;.&quot;); //$NON-NLS-1$&#xA;}&#xA;portString.append(getPort().getInterfaceElement().getName());&#xA;&#xA;return portString.toString();&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getResourceString" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getPort().getResource().getName();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getFBString" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getPort().getFb().getName();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getQualifiedString" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&#x9;&#x9;return getPortString();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//PortElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offline" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortElement">
    <eOperations name="getPortString" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="StringBuilder portString = new StringBuilder(getResource().getDevice().getName());&#xA;&#xA;portString.append(&quot;.&quot;); //$NON-NLS-1$&#xA;portString.append(resource.getName());&#xA;portString.append(&quot;.&quot;); //$NON-NLS-1$&#xA;&#xA;portString.append(getHierarchy());&#xA;&#xA;if (interfaceElement.eContainer() != null &amp;&amp; interfaceElement.eContainer().eContainer() instanceof AdapterFB) {&#xA;&#x9;portString.append(((PortElementImpl) eContainer()).interfaceElement.getName());&#xA;&#x9;portString.append(&quot;.&quot;); //$NON-NLS-1$&#xA;}&#xA;portString.append(interfaceElement.getName());&#xA;&#xA;return portString.toString();&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getDevice" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//Device">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&#x9;&#x9;return getResource().getDevice();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getSystem" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//AutomationSystem">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&#x9;&#x9;return getResource().getAutomationSystem();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fb" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//FBNetworkElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceElement" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//IInterfaceElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hierarchy" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IEditPartCreator" instanceClassName="org.eclipse.fordiac.ide.gef.editparts.IEditPartCreator"
      abstract="true" interface="true"/>
</ecore:EPackage>
