<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright (c) 2012 Profactor GmbH
  
 This program and the accompanying materials are made available under the
 terms of the Eclipse Public License 2.0 which is available at
 http://www.eclipse.org/legal/epl-2.0.

 SPDX-License-Identifier: EPL-2.0
 
 Contributors:
   Gerhard Ebenhofer
     - initial API and implementation and/or initial documentation
-->
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testdata"
    nsURI="at.ffg4iac.fbtester.model.testdata" nsPrefix="testdata">
  <eClassifiers xsi:type="ecore:EClass" name="TestData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="testName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testIntstance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventOutputs" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//ValuedVarDecl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" upperBound="-1"
        eType="#//ValuedVarDecl"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="line" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//FBType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValuedVarDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="varDeclaration" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//VarDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
