###############################################################################
# Copyright (c) 2026 ArSysOp and others
# 
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0/.
# 
# SPDX-License-Identifier: EPL-2.0
# 
# Contributors:
#   Alexander Fedorov (ArSysOp) - initial API and implementation
###############################################################################

featureName=Experimental 4diac IDE features
providerName=Eclipse 4diac
description=Prototype tool for automatic generation of FBs used for communication between devices and resources.
copyright=Copyright (c) 2026 Johannes Kepler University Linz\n\
\n\
This program and the accompanying materials are made\n\
available under the terms of the Eclipse Public License 2.0\n\
which is available at https://www.eclipse.org/legal/epl-2.0/\n\
\n\
SPDX-License-Identifier: EPL-2.0\n\
\n\
Contributors:\n\
  Alois Zoitl - initial API and implementation and/or initial documentation\n\
\n
