###############################################################################
# Copyright (c) 2026 ArSysOp and others
# 
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0/.
# 
# SPDX-License-Identifier: EPL-2.0
# 
# Contributors:
#   Alexander Fedorov (ArSysOp) - initial API and implementation
###############################################################################

featureName=Structured Text Feature
providerName=Eclipse 4diac
description=This feature provides support for IEC 61131-3 Structured Text.
copyright=Copyright (c) 2022, 2026 Martin Erich Jobst and others\n\
\n\
This program and the accompanying materials are made\n\
available under the terms of the Eclipse Public License 2.0\n\
which is available at https://www.eclipse.org/legal/epl-2.0/\n\
\n\
SPDX-License-Identifier: EPL-2.0\n\
\n\
Contributors:\n\
Martin Jobst\n\
- initial API and implementation and/or initial documentation\n\
\n
