<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="stfunction" nsURI="http://www.eclipse.org/fordiac/ide/structuredtextfunctioneditor/STFunction"
    nsPrefix="stfunction">
  <eClassifiers xsi:type="ecore:EClass" name="STFunctionSource" eSuperTypes="../../org.eclipse.fordiac.ide.structuredtextcore.model/model/STCore.ecore#//STSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.fordiac.ide.structuredtextcore.model/model/STCore.ecore#//STImport"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" upperBound="-1"
        eType="#//STFunction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="STFunction" eSuperTypes="../../org.eclipse.fordiac.ide.model/model/lib.ecore#//ICallable">
    <eOperations name="getInputParameters" upperBound="-1" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//ITypedElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.fordiac.ide.structuredtextfunctioneditor.stfunction.impl.STFunctionAnnotations.getInputParameters(this);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getOutputParameters" upperBound="-1" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//ITypedElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.fordiac.ide.structuredtextfunctioneditor.stfunction.impl.STFunctionAnnotations.getOutputParameters(this);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getInOutParameters" upperBound="-1" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//ITypedElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.fordiac.ide.structuredtextfunctioneditor.stfunction.impl.STFunctionAnnotations.getInOutParameters(this);"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/data.ecore#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="varDeclarations" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.fordiac.ide.structuredtextcore.model/model/STCore.ecore#//STVarDeclarationBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="code" upperBound="-1" eType="ecore:EClass ../../org.eclipse.fordiac.ide.structuredtextcore.model/model/STCore.ecore#//STStatement"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
