/*
 * generated by Xtext 2.26.0
 */
package org.eclipse.fordiac.ide.structuredtextfunctioneditor.ui.tests;

import com.google.inject.Injector;
import org.eclipse.fordiac.ide.structuredtextfunctioneditor.ui.internal.StructuredtextfunctioneditorActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class STFunctionUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StructuredtextfunctioneditorActivator.getInstance().getInjector("org.eclipse.fordiac.ide.structuredtextfunctioneditor.STFunction");
	}

}
