<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="OpSem" nsURI="http://OperationalSemantics/1.0" nsPrefix="opsem">
  <eClassifiers xsi:type="ecore:EClass" name="EventOccurrence">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignored" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fbRuntime" lowerBound="1"
        eType="#//FBRuntimeAbstract" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdTransactions" upperBound="-1"
        eType="#//Transaction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentFB" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//FBNetworkElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventManager">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel"/>
    <eOperations name="process">
      <eParameters name="eventManager" eType="#//EventManager"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transactions" upperBound="-1"
        eType="#//Transaction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="readyQueue" upperBound="-1"
        eType="#//Transaction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBRuntimeAbstract" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="How to manage to get the data? Three variants..."/>
    </eAnnotations>
    <eOperations name="run" upperBound="-1" eType="#//EventOccurrence">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="&#x9;&#x9;if (this.eContainer instanceof EventOccurrence) {&#xA;&#x9;&#x9;&#x9;return DefaultRunFBType.runFBType(this, (EventOccurrence) this.eContainer);&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;throw new IllegalArgumentException(&quot;The eContainer of the FBRuntimeAbstract object must be an EventOccurrence&quot;);&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getModel" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return null;"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicFBTypeRuntime" eSuperTypes="#//FBRuntimeAbstract">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel"/>
    <eOperations name="getModel" lowerBound="1" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//BasicFBType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return this.getBasicfbtype();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basicfbtype" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//BasicFBType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activeState" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//ECState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleFBTypeRuntime" eSuperTypes="#//FBRuntimeAbstract">
    <eOperations name="getModel" lowerBound="1" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//SimpleFBType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return simpleFBType;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simpleFBType" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//SimpleFBType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transaction" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputEventOccurrence" lowerBound="1"
        eType="#//EventOccurrence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBNetworkRuntime" eSuperTypes="#//FBRuntimeAbstract">
    <eOperations name="getModel" lowerBound="1" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//FBNetwork">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return this.getFbnetwork();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fbnetwork" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//FBNetwork"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transferData" upperBound="-1"
        eType="#//ConnectionToValueMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeRuntimes" upperBound="-1"
        eType="#//RuntimeMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBTransaction" eSuperTypes="#//Transaction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputEventOccurrences"
        upperBound="-1" eType="#//EventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputVariables" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//VarDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultFBRuntime" eType="#//FBRuntimeAbstract"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionToValueMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//Connection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="ecore:EClass ../../org.eclipse.fordiac.ide.model/model/lib.ecore#//FBNetworkElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//FBRuntimeAbstract"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
