/**
 * generated by Xtext 2.11.0
 */
package org.eclipse.fordiac.ide.model.structuredtext.structuredText;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.eclipse.fordiac.ide.model.structuredtext.structuredText.StructuredTextPackage#getType()
 * @model
 * @generated
 */
public enum Type implements Enumerator
{
  /**
   * The '<em><b>DINT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DINT_VALUE
   * @generated
   * @ordered
   */
  DINT(0, "DINT", "DINT"),

  /**
   * The '<em><b>INT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INT_VALUE
   * @generated
   * @ordered
   */
  INT(1, "INT", "INT"),

  /**
   * The '<em><b>SINT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SINT_VALUE
   * @generated
   * @ordered
   */
  SINT(2, "SINT", "SINT"),

  /**
   * The '<em><b>LINT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LINT_VALUE
   * @generated
   * @ordered
   */
  LINT(3, "LINT", "LINT"),

  /**
   * The '<em><b>UINT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UINT_VALUE
   * @generated
   * @ordered
   */
  UINT(4, "UINT", "UINT"),

  /**
   * The '<em><b>USINT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #USINT_VALUE
   * @generated
   * @ordered
   */
  USINT(5, "USINT", "USINT"),

  /**
   * The '<em><b>UDINT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UDINT_VALUE
   * @generated
   * @ordered
   */
  UDINT(6, "UDINT", "UDINT"),

  /**
   * The '<em><b>ULINT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ULINT_VALUE
   * @generated
   * @ordered
   */
  ULINT(7, "ULINT", "ULINT"),

  /**
   * The '<em><b>REAL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #REAL_VALUE
   * @generated
   * @ordered
   */
  REAL(8, "REAL", "REAL"),

  /**
   * The '<em><b>LREAL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LREAL_VALUE
   * @generated
   * @ordered
   */
  LREAL(9, "LREAL", "LREAL"),

  /**
   * The '<em><b>STRING</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STRING_VALUE
   * @generated
   * @ordered
   */
  STRING(10, "STRING", "STRING"),

  /**
   * The '<em><b>WSTRING</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WSTRING_VALUE
   * @generated
   * @ordered
   */
  WSTRING(11, "WSTRING", "WSTRING"),

  /**
   * The '<em><b>CHAR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CHAR_VALUE
   * @generated
   * @ordered
   */
  CHAR(12, "CHAR", "CHAR"),

  /**
   * The '<em><b>WCHAR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WCHAR_VALUE
   * @generated
   * @ordered
   */
  WCHAR(13, "WCHAR", "WCHAR"),

  /**
   * The '<em><b>TIME</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TIME_VALUE
   * @generated
   * @ordered
   */
  TIME(14, "TIME", "TIME"),

  /**
   * The '<em><b>LTIME</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LTIME_VALUE
   * @generated
   * @ordered
   */
  LTIME(15, "LTIME", "LTIME"),

  /**
   * The '<em><b>T</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #T_VALUE
   * @generated
   * @ordered
   */
  T(16, "T", "T"),

  /**
   * The '<em><b>LT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LT_VALUE
   * @generated
   * @ordered
   */
  LT(17, "LT", "LT"),

  /**
   * The '<em><b>TIME OF DAY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TIME_OF_DAY_VALUE
   * @generated
   * @ordered
   */
  TIME_OF_DAY(18, "TIME_OF_DAY", "TIME_OF_DAY"),

  /**
   * The '<em><b>LTIME OF DAY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LTIME_OF_DAY_VALUE
   * @generated
   * @ordered
   */
  LTIME_OF_DAY(19, "LTIME_OF_DAY", "LTIME_OF_DAY"),

  /**
   * The '<em><b>TOD</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TOD_VALUE
   * @generated
   * @ordered
   */
  TOD(20, "TOD", "TOD"),

  /**
   * The '<em><b>LTOD</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LTOD_VALUE
   * @generated
   * @ordered
   */
  LTOD(21, "LTOD", "LTOD"),

  /**
   * The '<em><b>DATE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DATE_VALUE
   * @generated
   * @ordered
   */
  DATE(22, "DATE", "DATE"),

  /**
   * The '<em><b>LDATE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LDATE_VALUE
   * @generated
   * @ordered
   */
  LDATE(23, "LDATE", "LDATE"),

  /**
   * The '<em><b>D</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #D_VALUE
   * @generated
   * @ordered
   */
  D(24, "D", "D"),

  /**
   * The '<em><b>LD</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LD_VALUE
   * @generated
   * @ordered
   */
  LD(25, "LD", "LD"),

  /**
   * The '<em><b>DATE AND TIME</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DATE_AND_TIME_VALUE
   * @generated
   * @ordered
   */
  DATE_AND_TIME(26, "DATE_AND_TIME", "DATE_AND_TIME"),

  /**
   * The '<em><b>LDATE AND TIME</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LDATE_AND_TIME_VALUE
   * @generated
   * @ordered
   */
  LDATE_AND_TIME(27, "LDATE_AND_TIME", "LDATE_AND_TIME"),

  /**
   * The '<em><b>DT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DT_VALUE
   * @generated
   * @ordered
   */
  DT(28, "DT", "DT"),

  /**
   * The '<em><b>LDT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LDT_VALUE
   * @generated
   * @ordered
   */
  LDT(29, "LDT", "LDT"),

  /**
   * The '<em><b>BOOL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BOOL_VALUE
   * @generated
   * @ordered
   */
  BOOL(30, "BOOL", "BOOL"),

  /**
   * The '<em><b>BYTE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BYTE_VALUE
   * @generated
   * @ordered
   */
  BYTE(31, "BYTE", "BYTE"),

  /**
   * The '<em><b>WORD</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WORD_VALUE
   * @generated
   * @ordered
   */
  WORD(32, "WORD", "WORD"),

  /**
   * The '<em><b>DWORD</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DWORD_VALUE
   * @generated
   * @ordered
   */
  DWORD(33, "DWORD", "DWORD"),

  /**
   * The '<em><b>LWORD</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LWORD_VALUE
   * @generated
   * @ordered
   */
  LWORD(34, "LWORD", "LWORD");

  /**
   * The '<em><b>DINT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DINT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DINT
   * @model
   * @generated
   * @ordered
   */
  public static final int DINT_VALUE = 0;

  /**
   * The '<em><b>INT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>INT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INT
   * @model
   * @generated
   * @ordered
   */
  public static final int INT_VALUE = 1;

  /**
   * The '<em><b>SINT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SINT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SINT
   * @model
   * @generated
   * @ordered
   */
  public static final int SINT_VALUE = 2;

  /**
   * The '<em><b>LINT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LINT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LINT
   * @model
   * @generated
   * @ordered
   */
  public static final int LINT_VALUE = 3;

  /**
   * The '<em><b>UINT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>UINT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #UINT
   * @model
   * @generated
   * @ordered
   */
  public static final int UINT_VALUE = 4;

  /**
   * The '<em><b>USINT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>USINT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #USINT
   * @model
   * @generated
   * @ordered
   */
  public static final int USINT_VALUE = 5;

  /**
   * The '<em><b>UDINT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>UDINT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #UDINT
   * @model
   * @generated
   * @ordered
   */
  public static final int UDINT_VALUE = 6;

  /**
   * The '<em><b>ULINT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ULINT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ULINT
   * @model
   * @generated
   * @ordered
   */
  public static final int ULINT_VALUE = 7;

  /**
   * The '<em><b>REAL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>REAL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #REAL
   * @model
   * @generated
   * @ordered
   */
  public static final int REAL_VALUE = 8;

  /**
   * The '<em><b>LREAL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LREAL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LREAL
   * @model
   * @generated
   * @ordered
   */
  public static final int LREAL_VALUE = 9;

  /**
   * The '<em><b>STRING</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>STRING</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #STRING
   * @model
   * @generated
   * @ordered
   */
  public static final int STRING_VALUE = 10;

  /**
   * The '<em><b>WSTRING</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>WSTRING</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #WSTRING
   * @model
   * @generated
   * @ordered
   */
  public static final int WSTRING_VALUE = 11;

  /**
   * The '<em><b>CHAR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>CHAR</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CHAR
   * @model
   * @generated
   * @ordered
   */
  public static final int CHAR_VALUE = 12;

  /**
   * The '<em><b>WCHAR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>WCHAR</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #WCHAR
   * @model
   * @generated
   * @ordered
   */
  public static final int WCHAR_VALUE = 13;

  /**
   * The '<em><b>TIME</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TIME</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TIME
   * @model
   * @generated
   * @ordered
   */
  public static final int TIME_VALUE = 14;

  /**
   * The '<em><b>LTIME</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LTIME</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LTIME
   * @model
   * @generated
   * @ordered
   */
  public static final int LTIME_VALUE = 15;

  /**
   * The '<em><b>T</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>T</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #T
   * @model
   * @generated
   * @ordered
   */
  public static final int T_VALUE = 16;

  /**
   * The '<em><b>LT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LT
   * @model
   * @generated
   * @ordered
   */
  public static final int LT_VALUE = 17;

  /**
   * The '<em><b>TIME OF DAY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TIME OF DAY</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TIME_OF_DAY
   * @model
   * @generated
   * @ordered
   */
  public static final int TIME_OF_DAY_VALUE = 18;

  /**
   * The '<em><b>LTIME OF DAY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LTIME OF DAY</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LTIME_OF_DAY
   * @model
   * @generated
   * @ordered
   */
  public static final int LTIME_OF_DAY_VALUE = 19;

  /**
   * The '<em><b>TOD</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TOD</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TOD
   * @model
   * @generated
   * @ordered
   */
  public static final int TOD_VALUE = 20;

  /**
   * The '<em><b>LTOD</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LTOD</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LTOD
   * @model
   * @generated
   * @ordered
   */
  public static final int LTOD_VALUE = 21;

  /**
   * The '<em><b>DATE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DATE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DATE
   * @model
   * @generated
   * @ordered
   */
  public static final int DATE_VALUE = 22;

  /**
   * The '<em><b>LDATE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LDATE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LDATE
   * @model
   * @generated
   * @ordered
   */
  public static final int LDATE_VALUE = 23;

  /**
   * The '<em><b>D</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>D</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #D
   * @model
   * @generated
   * @ordered
   */
  public static final int D_VALUE = 24;

  /**
   * The '<em><b>LD</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LD</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LD
   * @model
   * @generated
   * @ordered
   */
  public static final int LD_VALUE = 25;

  /**
   * The '<em><b>DATE AND TIME</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DATE AND TIME</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DATE_AND_TIME
   * @model
   * @generated
   * @ordered
   */
  public static final int DATE_AND_TIME_VALUE = 26;

  /**
   * The '<em><b>LDATE AND TIME</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LDATE AND TIME</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LDATE_AND_TIME
   * @model
   * @generated
   * @ordered
   */
  public static final int LDATE_AND_TIME_VALUE = 27;

  /**
   * The '<em><b>DT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DT
   * @model
   * @generated
   * @ordered
   */
  public static final int DT_VALUE = 28;

  /**
   * The '<em><b>LDT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LDT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LDT
   * @model
   * @generated
   * @ordered
   */
  public static final int LDT_VALUE = 29;

  /**
   * The '<em><b>BOOL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>BOOL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #BOOL
   * @model
   * @generated
   * @ordered
   */
  public static final int BOOL_VALUE = 30;

  /**
   * The '<em><b>BYTE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>BYTE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #BYTE
   * @model
   * @generated
   * @ordered
   */
  public static final int BYTE_VALUE = 31;

  /**
   * The '<em><b>WORD</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>WORD</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #WORD
   * @model
   * @generated
   * @ordered
   */
  public static final int WORD_VALUE = 32;

  /**
   * The '<em><b>DWORD</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DWORD</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DWORD
   * @model
   * @generated
   * @ordered
   */
  public static final int DWORD_VALUE = 33;

  /**
   * The '<em><b>LWORD</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LWORD</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LWORD
   * @model
   * @generated
   * @ordered
   */
  public static final int LWORD_VALUE = 34;

  /**
   * An array of all the '<em><b>Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Type[] VALUES_ARRAY =
    new Type[]
    {
      DINT,
      INT,
      SINT,
      LINT,
      UINT,
      USINT,
      UDINT,
      ULINT,
      REAL,
      LREAL,
      STRING,
      WSTRING,
      CHAR,
      WCHAR,
      TIME,
      LTIME,
      T,
      LT,
      TIME_OF_DAY,
      LTIME_OF_DAY,
      TOD,
      LTOD,
      DATE,
      LDATE,
      D,
      LD,
      DATE_AND_TIME,
      LDATE_AND_TIME,
      DT,
      LDT,
      BOOL,
      BYTE,
      WORD,
      DWORD,
      LWORD,
    };

  /**
   * A public read-only list of all the '<em><b>Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Type> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Type get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Type result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Type getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Type result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Type get(int value)
  {
    switch (value)
    {
      case DINT_VALUE: return DINT;
      case INT_VALUE: return INT;
      case SINT_VALUE: return SINT;
      case LINT_VALUE: return LINT;
      case UINT_VALUE: return UINT;
      case USINT_VALUE: return USINT;
      case UDINT_VALUE: return UDINT;
      case ULINT_VALUE: return ULINT;
      case REAL_VALUE: return REAL;
      case LREAL_VALUE: return LREAL;
      case STRING_VALUE: return STRING;
      case WSTRING_VALUE: return WSTRING;
      case CHAR_VALUE: return CHAR;
      case WCHAR_VALUE: return WCHAR;
      case TIME_VALUE: return TIME;
      case LTIME_VALUE: return LTIME;
      case T_VALUE: return T;
      case LT_VALUE: return LT;
      case TIME_OF_DAY_VALUE: return TIME_OF_DAY;
      case LTIME_OF_DAY_VALUE: return LTIME_OF_DAY;
      case TOD_VALUE: return TOD;
      case LTOD_VALUE: return LTOD;
      case DATE_VALUE: return DATE;
      case LDATE_VALUE: return LDATE;
      case D_VALUE: return D;
      case LD_VALUE: return LD;
      case DATE_AND_TIME_VALUE: return DATE_AND_TIME;
      case LDATE_AND_TIME_VALUE: return LDATE_AND_TIME;
      case DT_VALUE: return DT;
      case LDT_VALUE: return LDT;
      case BOOL_VALUE: return BOOL;
      case BYTE_VALUE: return BYTE;
      case WORD_VALUE: return WORD;
      case DWORD_VALUE: return DWORD;
      case LWORD_VALUE: return LWORD;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Type(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Type
