/**
 * generated by Xtext 2.25.0
 */
package org.eclipse.fordiac.ide.model.structuredtext.structuredText;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.eclipse.fordiac.ide.model.structuredtext.structuredText.StructuredTextPackage#getType()
 * @model
 * @generated
 */
public enum Type implements Enumerator
{
  /**
	 * The '<em><b>DINT</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #DINT_VALUE
	 * @generated
	 * @ordered
	 */
  DINT(0, "DINT", "DINT"),

  /**
	 * The '<em><b>INT</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #INT_VALUE
	 * @generated
	 * @ordered
	 */
  INT(1, "INT", "INT"),

  /**
	 * The '<em><b>SINT</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #SINT_VALUE
	 * @generated
	 * @ordered
	 */
  SINT(2, "SINT", "SINT"),

  /**
	 * The '<em><b>LINT</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #LINT_VALUE
	 * @generated
	 * @ordered
	 */
  LINT(3, "LINT", "LINT"),

  /**
	 * The '<em><b>UINT</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #UINT_VALUE
	 * @generated
	 * @ordered
	 */
  UINT(4, "UINT", "UINT"),

  /**
	 * The '<em><b>USINT</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #USINT_VALUE
	 * @generated
	 * @ordered
	 */
  USINT(5, "USINT", "USINT"),

  /**
	 * The '<em><b>UDINT</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #UDINT_VALUE
	 * @generated
	 * @ordered
	 */
  UDINT(6, "UDINT", "UDINT"),

  /**
	 * The '<em><b>ULINT</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #ULINT_VALUE
	 * @generated
	 * @ordered
	 */
  ULINT(7, "ULINT", "ULINT"),

  /**
	 * The '<em><b>REAL</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #REAL_VALUE
	 * @generated
	 * @ordered
	 */
  REAL(8, "REAL", "REAL"),

  /**
	 * The '<em><b>LREAL</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #LREAL_VALUE
	 * @generated
	 * @ordered
	 */
  LREAL(9, "LREAL", "LREAL"),

  /**
	 * The '<em><b>STRING</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #STRING_VALUE
	 * @generated
	 * @ordered
	 */
  STRING(10, "STRING", "STRING"),

  /**
	 * The '<em><b>WSTRING</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #WSTRING_VALUE
	 * @generated
	 * @ordered
	 */
  WSTRING(11, "WSTRING", "WSTRING"),

  /**
	 * The '<em><b>CHAR</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #CHAR_VALUE
	 * @generated
	 * @ordered
	 */
  CHAR(12, "CHAR", "CHAR"),

  /**
	 * The '<em><b>WCHAR</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #WCHAR_VALUE
	 * @generated
	 * @ordered
	 */
  WCHAR(13, "WCHAR", "WCHAR"),

  /**
	 * The '<em><b>BOOL</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #BOOL_VALUE
	 * @generated
	 * @ordered
	 */
  BOOL(14, "BOOL", "BOOL"),

  /**
	 * The '<em><b>BYTE</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #BYTE_VALUE
	 * @generated
	 * @ordered
	 */
  BYTE(15, "BYTE", "BYTE"),

  /**
	 * The '<em><b>WORD</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #WORD_VALUE
	 * @generated
	 * @ordered
	 */
  WORD(16, "WORD", "WORD"),

  /**
	 * The '<em><b>DWORD</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #DWORD_VALUE
	 * @generated
	 * @ordered
	 */
  DWORD(17, "DWORD", "DWORD"),

  /**
	 * The '<em><b>LWORD</b></em>' literal object.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #LWORD_VALUE
	 * @generated
	 * @ordered
	 */
  LWORD(18, "LWORD", "LWORD");

  /**
	 * The '<em><b>DINT</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #DINT
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int DINT_VALUE = 0;

  /**
	 * The '<em><b>INT</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #INT
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int INT_VALUE = 1;

  /**
	 * The '<em><b>SINT</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #SINT
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int SINT_VALUE = 2;

  /**
	 * The '<em><b>LINT</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #LINT
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int LINT_VALUE = 3;

  /**
	 * The '<em><b>UINT</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #UINT
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int UINT_VALUE = 4;

  /**
	 * The '<em><b>USINT</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #USINT
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int USINT_VALUE = 5;

  /**
	 * The '<em><b>UDINT</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #UDINT
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int UDINT_VALUE = 6;

  /**
	 * The '<em><b>ULINT</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #ULINT
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int ULINT_VALUE = 7;

  /**
	 * The '<em><b>REAL</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #REAL
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int REAL_VALUE = 8;

  /**
	 * The '<em><b>LREAL</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #LREAL
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int LREAL_VALUE = 9;

  /**
	 * The '<em><b>STRING</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #STRING
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int STRING_VALUE = 10;

  /**
	 * The '<em><b>WSTRING</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #WSTRING
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int WSTRING_VALUE = 11;

  /**
	 * The '<em><b>CHAR</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #CHAR
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int CHAR_VALUE = 12;

  /**
	 * The '<em><b>WCHAR</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #WCHAR
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int WCHAR_VALUE = 13;

  /**
	 * The '<em><b>BOOL</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #BOOL
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int BOOL_VALUE = 14;

  /**
	 * The '<em><b>BYTE</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #BYTE
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int BYTE_VALUE = 15;

  /**
	 * The '<em><b>WORD</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #WORD
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int WORD_VALUE = 16;

  /**
	 * The '<em><b>DWORD</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #DWORD
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int DWORD_VALUE = 17;

  /**
	 * The '<em><b>LWORD</b></em>' literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #LWORD
	 * @model
	 * @generated
	 * @ordered
	 */
  public static final int LWORD_VALUE = 18;

  /**
	 * An array of all the '<em><b>Type</b></em>' enumerators.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  private static final Type[] VALUES_ARRAY =
    new Type[] {
			DINT,
			INT,
			SINT,
			LINT,
			UINT,
			USINT,
			UDINT,
			ULINT,
			REAL,
			LREAL,
			STRING,
			WSTRING,
			CHAR,
			WCHAR,
			BOOL,
			BYTE,
			WORD,
			DWORD,
			LWORD,
		};

  /**
	 * A public read-only list of all the '<em><b>Type</b></em>' enumerators.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public static final List<Type> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
	 * Returns the '<em><b>Type</b></em>' literal with the specified literal value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param literal the literal.
	 * @return the matching enumerator or <code>null</code>.
	 * @generated
	 */
  public static Type get(String literal)
  {
		for (int i = 0; i < VALUES_ARRAY.length; ++i) {
			Type result = VALUES_ARRAY[i];
			if (result.toString().equals(literal)) {
				return result;
			}
		}
		return null;
	}

  /**
	 * Returns the '<em><b>Type</b></em>' literal with the specified name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param name the name.
	 * @return the matching enumerator or <code>null</code>.
	 * @generated
	 */
  public static Type getByName(String name)
  {
		for (int i = 0; i < VALUES_ARRAY.length; ++i) {
			Type result = VALUES_ARRAY[i];
			if (result.getName().equals(name)) {
				return result;
			}
		}
		return null;
	}

  /**
	 * Returns the '<em><b>Type</b></em>' literal with the specified integer value.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the integer value.
	 * @return the matching enumerator or <code>null</code>.
	 * @generated
	 */
  public static Type get(int value)
  {
		switch (value) {
			case DINT_VALUE: return DINT;
			case INT_VALUE: return INT;
			case SINT_VALUE: return SINT;
			case LINT_VALUE: return LINT;
			case UINT_VALUE: return UINT;
			case USINT_VALUE: return USINT;
			case UDINT_VALUE: return UDINT;
			case ULINT_VALUE: return ULINT;
			case REAL_VALUE: return REAL;
			case LREAL_VALUE: return LREAL;
			case STRING_VALUE: return STRING;
			case WSTRING_VALUE: return WSTRING;
			case CHAR_VALUE: return CHAR;
			case WCHAR_VALUE: return WCHAR;
			case BOOL_VALUE: return BOOL;
			case BYTE_VALUE: return BYTE;
			case WORD_VALUE: return WORD;
			case DWORD_VALUE: return DWORD;
			case LWORD_VALUE: return LWORD;
			default: return null;
		}
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  private final int value;

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  private final String name;

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  private final String literal;

  /**
	 * Only this class can construct instances.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  private Type(int value, String name, String literal)
  {
		this.value = value;
		this.name = name;
		this.literal = literal;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public int getValue()
  {
	  return value;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public String getName()
  {
	  return name;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public String getLiteral()
  {
	  return literal;
	}

  /**
	 * Returns the literal value of the enumerator, which is its string representation.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public String toString()
  {
		return literal;
	}
  
} //Type
