###############################################################################
# Copyright (c) 2026 ArSysOp and others
# 
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0/.
# 
# SPDX-License-Identifier: EPL-2.0
# 
# Contributors:
#   Alexander Fedorov (ArSysOp) - initial API and implementation
###############################################################################

featureName=Function Block Type Editor
providerName=Eclipse 4diac
description=This feature contains the function block type editing functionality of 4diac IDE.
copyright=Copyright (c) 2011, 2026 Profactor GmbH, TU Wien ACIN, fortiss GmbH and others\n\
\n\
This program and the accompanying materials are made\n\
available under the terms of the Eclipse Public License 2.0\n\
which is available at https://www.eclipse.org/legal/epl-2.0/\n\
\n\
SPDX-License-Identifier: EPL-2.0\n\
\n\
Contributors:\n\
Gerhard Ebenhofer, Gerd Kainz, Alois Zoitl, Ingo Hegny, Waldemar Eisenmenger, Monika Wenger\n\
- initial API and implementation and/or initial documentation\n\
\n
