/*
 * generated by Xtext 2.29.0
 */
package org.eclipse.fordiac.ide.globalconstantseditor.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.fordiac.ide.globalconstantseditor.parser.antlr.internal.InternalGlobalConstantsParser;
import org.eclipse.fordiac.ide.globalconstantseditor.services.GlobalConstantsGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GlobalConstantsParser extends AbstractAntlrParser {

	@Inject
	private GlobalConstantsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGlobalConstantsParser createParser(XtextTokenStream stream) {
		return new InternalGlobalConstantsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "STGlobalConstsSource";
	}

	public GlobalConstantsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GlobalConstantsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
