/*
 * generated by Xtext 2.29.0
 */
package org.eclipse.fordiac.ide.globalconstantseditor.scoping;

import org.eclipse.fordiac.ide.structuredtextcore.scoping.STCoreScopeProvider;

public abstract class AbstractGlobalConstantsScopeProvider extends STCoreScopeProvider {
}
