name: 4diac IDE verification build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions: {}

jobs:
  event_file:
    name: "Upload Event File"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: event_file
        path: ${{ github.event_path }}

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [21]
    runs-on: ${{ matrix.os }}
    name: OS ${{ matrix.os }} Java ${{ matrix.java }} compile
    permissions:
      # required for all workflows
      security-events: write
      # required to fetch internal or private CodeQL packs
      packages: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Initialize CodeQL
      uses: github/codeql-action/init@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3
      with:
        languages: java-kotlin
        build-mode: manual

    - name: Set up Java
      uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'

    - name: Set up Maven
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
      with:
        maven-version: 3.9.11

    - name: Build with Maven
      uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3 # v1.0.1
      with:
       run: >-
        mvn -V -B -fae -ntp clean verify

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
      with:
        category: "/language:java-kotlin"

    - name: Upload Test Results for Java-${{ matrix.java }}
      if: always()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: test-results-${{ matrix.os }}-java${{ matrix.java }}
        if-no-files-found: error
        path: |
          ${{ github.workspace }}/**/target/surefire-reports/*.xml
