name: Publish 4diac IDE Unit Test Results

on:
  workflow_run:
    workflows: ["4diac IDE verification build"]
    types:
      - completed

permissions:
  checks: write
  pull-requests: write
  contents: read
  issues: read
  actions: read

jobs:
  unit-test-results:
    name: Unit Test Results
    runs-on: ubuntu-latest
    if: >-
      github.event.workflow_run.conclusion == 'success' ||
      github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: Download and Extract Artifacts
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
           mkdir -p artifacts && cd artifacts
           gh run download ${{ github.event.workflow_run.id }} --repo ${{ github.repository }} \
             --name 'event_file' --pattern 'test-results-*'

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        with:
          check_name: >-
            Test Results (${{ github.event.workflow_run.event || github.event_name }})
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/event_file/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: "artifacts/**/*.xml"
